### ISSUE TITLE
./ as part of input filename causes problems

### ISSUE THREAD

**Issue by bramton** [ImageMagick/png#1]
I am trying to use `find . -name "*.png" -exec pngfix --strip=all --prefix=fix_ {} \;` but it does not understand the `./` in front of the filename.

This works fine:
`pngfix --strip=all --prefix=fix_ bla_16.png `

But this gives an error:
`pngfix --strip=all --prefix=fix_ ./bla_16.png`

Error:
`fix_./bla_16.png: No such file or directory`

**Comment by dlemstra** [comment]
You should not open issues in this repository. Post it in: https://github.com/glennrp/libpng instead
